void sound()
{
  textSize(14);
  
  if(keyPressed==true)
  {
    if(key=='9')                              
    {
      if(High)
      {
        B=B-1;
      }
      if(Low)
      {
        A=A-1;
      }
      if(ab)
      {
        AB=AB-1;
      }
      if(ba)
      {
        BA=BA-1;
      }
      if(at)
      {
        attackTime=attackTime - 0.001;
      }
      if(st)
      {
        sustainTime=sustainTime - 0.001;
      }
      if(sl)
      {
        sustainLevel=sustainLevel - 0.001;
      }
      if(rt)
      {
        releaseTime=releaseTime - 0.001;
      }
    }                                                          
    if(key=='0')                                
    {
      if(High)
      {
        B=B+1;
      }
      if(Low)
      {
        A=A+1;
      }
      if(ab)
      {
        AB=AB+1;
      }
      if(ba)
      {
        BA=BA+1;
      }
      if(at)
      {
        attackTime=attackTime + 0.001;
      }
      if(st)
      {
        sustainTime=sustainTime + 0.001;
      }
      if(sl)
      {
        sustainLevel=sustainLevel + 0.001;
      }
      if(rt)
      {
        releaseTime=releaseTime + 0.001;
      }
    }                            
    if(key=='1')
    {
      Oct1 =true;
      Oct2=false;
      Oct3=false;
    }
    if(key=='2')
    {
      Oct1 =false;
      Oct2=true;
      Oct3=false;
    }
    if(key=='3')
    {
      Oct1 =false;
      Oct2=false;
      Oct3=true;
    }
    if(Oct1)                
    {      
      if(PitchMod)
      {
        oct=mouseX;
        W=15.55;
        S=32.06;
        E=49.5;
        D=68;
        F=87.6;
        T=108.36;
        G=130.37;
        Y=153.67;
        H=178.37;
        U=204.53;
        J=232.25;
        K=261.62;
      }
      else
      {
        oct=261.63;
        W=15.55;
        S=32.06;
        E=49.5;
        D=68;
        F=87.6;
        T=108.36;
        G=130.37;
        Y=153.67;
        H=178.37;
        U=204.53;
        J=232.25;
        K=261.62;
      }
      
    }
    if(Oct2)
    {
      if(PitchMod)
      {
        oct=mouseX;
        W=31.12;
        S=64.08;
        E=99;
        D=136;
        F=175.21;
        T=216.74;
        G=260.74;
        Y=307.36;
        H=356.75;
        U=409.08;
        J=464.52;
        K=523.25;
      }
      else
      {
        oct=523.25;
        W=31.12;
        S=64.08;
        E=99;
        D=136;
        F=175.21;
        T=216.74;
        G=260.74;
        Y=307.36;
        H=356.75;
        U=409.08;
        J=464.52;
        K=523.25;
      }
    }
    if(Oct3)
    {
      if(PitchMod)
      {
        oct=mouseX;
        W=62.23;
        S=128.16;
        E=198.01;
        D=272.01;
        F=350.41;
        T=433.48;
        G=521.48;
        Y=614.72;
        H=713.5;
        U=818.16;
        J=929.03;
        K=1046.5;
      }
      else
      {
        oct=1046.52;
        W=62.23;
        S=128.16;
        E=198.01;
        D=272.01;
        F=350.41;
        T=433.48;
        G=521.48;
        Y=614.72;
        H=713.5;
        U=818.16;
        J=929.03;
        K=1046.5;
      }
    }
    
    if(Vibrato)   
    {
      if(count==0)
      {
        oct=oct+20;
      }
      if(count==2)
      {
        oct=oct-20;
        count=0;
      }
      count++;
    }
      
    if(Sin)
    {
      if(key=='a')   
      {
        a.play();
        a.freq(oct);
      }
      if(key=='w')
      {
        a.play();
        a.freq(oct+W);

      }
      if(key=='s')
      {
        a.play();
        a.freq(oct+S);
      }
      if(key=='e')
      {
        a.play();
        a.freq(oct+E);
      }
      if(key=='d')
      {
        a.play();
        a.freq(oct+D);
      }
      if(key=='f')
      {
        a.play();
        a.freq(oct+F);
      }
      if(key=='t')
      {
        a.play();
        a.freq(oct+T);
      }
      if(key=='g')
      {
        a.play();
        a.freq(oct+G);
      }
      if(key=='y')
      {
        a.play();
        a.freq(oct+Y);
      }
      if(key=='h')
      {
        a.play();
        a.freq(oct+H);
      }
      if(key=='u')
      {
        a.play();
        a.freq(oct+U);
      }
      if(key=='j')
      {
        a.play();
        a.freq(oct+J);
      }
      if(key=='k')
      {
        a.play();
        a.freq(oct+K);
      }
    }  //end of Sin wave
    if(Saw)
    {
      if(key=='a')    
      {
        aa.play();
        aa.freq(oct);
      }
      if(key=='w')
      {
        aa.play();
        aa.freq(oct+W);
      }
      if(key=='s')
      {
        aa.play();
        aa.freq(oct+S);
      }
      if(key=='e')
      {
        aa.play();
        aa.freq(oct+E);
      }
      if(key=='d')
      {
        aa.play();
        aa.freq(oct+D);
      }
      if(key=='f')
      {
        aa.play();
        aa.freq(oct+F);
      }
      if(key=='t')
      {
        aa.play();
        aa.freq(oct+T);
      }
      if(key=='g')
      {
        aa.play();
        aa.freq(oct+G);
      }
      if(key=='y')
      {
        aa.play();
        aa.freq(oct+Y);
      }
      if(key=='h')
      {
        aa.play();
        aa.freq(oct+H);
      }
      if(key=='u')
      {
        aa.play();
        aa.freq(oct+U);
      }
      if(key=='j')
      {
        aa.play();
        aa.freq(oct+J);
      }
      if(key=='k')
      {
        aa.play();
        aa.freq(oct+K);
      }
    }                            
    if(Tri)
    {
      if(key=='a')    //note c
      {
        aaa.play();
        aaa.freq(oct);
      }
      if(key=='w')
      {
        aaa.play();
        aaa.freq(oct+W);
      }
      if(key=='s')
      {
        aaa.play();
        aaa.freq(oct+S);
      }
      if(key=='e')
      {
        aaa.play();
        aaa.freq(oct+E);
      }
      if(key=='d')
      {
        aaa.play();
        aaa.freq(oct+D);
      }
      if(key=='f')
      {
        aaa.play();
        aaa.freq(oct+F);
      }
      if(key=='t')
      {
        aaa.play();
        aaa.freq(oct+T);
      }
      if(key=='g')
      {
        aaa.play();
        aaa.freq(oct+G);
      }
      if(key=='y')
      {
        aaa.play();
        aaa.freq(oct+Y);
      }
      if(key=='h')
      {
        aaa.play();
        aaa.freq(oct+H);
      }
      if(key=='u')
      {
        aaa.play();
        aaa.freq(oct+U);
      }
      if(key=='j')
      {
        aaa.play();
        aaa.freq(oct+J);
      }
      if(key=='k')
      {
        aaa.play();
        aaa.freq(oct+K);
      }
    }          // end
  }

  if(Sin)
  {
    Saw=false;
    Tri=false;
  }
  if(Saw)
  {
    Sin=false;
    Tri=false;
  }
  if(Tri)
  {
    Saw=false;
    Sin=false;
  }
  if(keyPressed)
  {
    if(key!=0 || key!=9)
    {
      Env=true;
    }
  }
  if(Env)
  {
    if(Sin)
    {
      env.play(a, attackTime, sustainTime, sustainLevel, releaseTime);  // Refer to https://processing.org/reference/libraries/sound/Env.html   
    }
    if(Saw)
    {
      env.play(aa, attackTime, sustainTime, sustainLevel, releaseTime);
    }
    if(Tri)
    {
      env.play(aaa, attackTime, sustainTime, sustainLevel, releaseTime);
    }
  }
  if(Low)
  {
    if(Sin)
    {
      lowPass.process(a);        
    }
    if(Saw)
    {
      lowPass.process(aa);
    }
    if(Tri)
    {
      lowPass.process(aaa);
    }
    lowPass.freq(A);
  }
  if(High)
  {
    if(Sin)
    {
      highPass.process(a);
    }
    if(Saw)
    {
      highPass.process(aa);
    }
    if(Tri)
    {
      highPass.process(aaa);
    }
    highPass.freq(B);
  }
  if(Band)
  {
    if(Sin)
    {
      bandPass.process(a,AB,BA);
    }
    if(Saw)
    {
      bandPass.process(aa,AB,BA);
    }
    if(Tri)
    {
      bandPass.process(aaa,AB,BA);
    }
  }
  allText();      
}
